version: "3.8"

services:
  mongodb-primary:
    image: mongo:7
    container_name: mongodb-primary
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    command: >
      mongod --replSet rs0 --bind_ip_all --port 27017
    volumes:
      - mongodb_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - datalake-network

  mongodb-secondary:
    image: mongo:7
    container_name: mongodb-secondary
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    command: >
      mongod --replSet rs0 --bind_ip_all --port 27017
    depends_on:
      - mongodb-primary
    networks:
      - datalake-network

volumes:
  mongodb_data:

networks:
  datalake-network:
    driver: bridge
