version: "3.8"

services:
  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: aula04-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass password123
    volumes:
      - redis_data:/data

  # Redis Sentinel (para HA)
  redis-sentinel:
    image: redis:7.2-alpine
    container_name: aula04-redis-sentinel
    restart: unless-stopped
    ports:
      - "26379:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis

  # API .NET
  api:
    build: .
    container_name: aula04-redis-api
    restart: unless-stopped
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - Redis__Password=password123
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - redis

volumes:
  redis_data:
