services:
  postgres:
    image: postgres:16-alpine
    container_name: aula011-postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pedidosdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pguser"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgres:/docker-entrypoint-initdb.d

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aula011-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "SqlServer!Pass123"
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "SqlServer!Pass123",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssqldata:/var/opt/mssql
      - ./init-sqlserver:/init-sqlserver

volumes:
  pgdata:
  mssqldata:

networks:
  default:
    name: aula011-network
